techsport:
  front-url: "http://localhost:4200"
  database:
    name: "techsport-dev"
  strava:
    url:
      api: "https://www.strava.com/api/"
      oauth: "https://www.strava.com/oauth/authorize"
      redirect: "http://localhost:${server.port}/api/strava/callback"